### ISSUE TITLE
'int' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by dboyd13** [gelim/censys#1]
Hi there - I get the following error - any ideas?

```
$ ./censys_io.py "censys.io"                                                                                                             
Number of results: 12                                                                                                                                 
Traceback (most recent call last):                                                                                                                    
  File "censys_io.py", line 327, in <module>                                                                                                          
    print_short(e)                                                                                                                                    
  File "censys_io.py", line 61, in print_short                                                                                                        
    as_num = res.get('autonomous_system.asn', [''])[0]                                                                                                
TypeError: 'int' object has no attribute '__getitem__'
```
Verbose queries work ok:

```
$ ./censys_io.py "censys.io" --limit 1 --verbose                                                                                         
Number of results: 12                                                                                                                                 
{u'443': {u'https': {u'dhe': {u'metadata': {}, u'support': False},                                                                                    
                     u'dhe_export': {u'metadata': {}, u'support': False},                                                                             
                     u'heartbleed': {u'heartbeat_enabled': False,                                                                                     
                                     u'heartbleed_vulnerable': False,                                                                                 
                                     u'metadata': {}},                                                                                                
                     u'rsa_export': {u'metadata': {}, u'support': False},
<snip>
```
Versions

gelim/censys version: ````99c1a3b4d3831e7bcedd4185f4d7476a4701c0cf````
censys:

````$ pip show censys                                                                                                                     
Name: censys                                                                                                                                          
Version: 0.0.7 ````

**Comment by gelim** [comment]
Hi, sorry I see that a little bit late.
There was an API breakage from censys, I did fix that some weeks ago.

```
$ ./censys_io.py "censys.io" 
Number of results: 11
141.212.118.9   Title: N/A                                        SSL: kafka-1.censys.io                            AS: UMICH-AS-5 (36375)                  Loc: US / Ann Arbor           OS: N/A        Tags: http, https
141.212.118.129 Title: N/A                                        SSL: es-frontend-1.censys.io                      AS: UMICH-AS-5 (36375)                  Loc: US / Ann Arbor           OS: N/A        Tags: http, https
141.212.118.130 Title: N/A                                        SSL: es-frontend-2.censys.io                      AS: UMICH-AS-5 (36375)                  Loc: US / Ann Arbor           OS: N/A        Tags: http, https
104.237.146.167 Title: CloudPiercer                               SSL: cloudpiercer.org + cloudpiercer.org+         AS: LINODE-AP (63949)                   Loc: US / Absecon             OS: N/A        Tags: http, smtp, ssh, https
141.212.118.20  Title: Internet-Wide Scan Data Repository         SSL: scans.io + scans.io+                         AS: UMICH-AS-5 (36375)                  Loc: US / Ann Arbor           OS: Ubuntu     Tags: http, ssh, https
141.212.118.17  Title: Internet-Wide Scan Data Repository         SSL: scans.io + scans.io+                         AS: UMICH-AS-5 (36375)                  Loc: US / Ann Arbor           OS: Ubuntu     Tags: http, ssh, https
93.29.245.86    Title: Lazarius Reborn                            SSL:                                              AS: LDCOMNET, (15557)                   Loc: FR /                     OS: Unix       Tags: http
92.177.120.127  Title: Seguridad, Linux y dems frikerias          SSL:                                              AS: UNI2-AS, (12479)                    Loc: ES / Elda                OS: N/A        Tags: http, smtp
192.157.221.105 Title:  &#8211; Hello, everyone                   SSL:                                              AS: ENZUINC-US (18978)                  Loc: US / Los Angeles         OS: Ubuntu     Tags: http, smtp, ssh
192.157.221.106 Title:  &#8211; Hello, everyone                   SSL:                                              AS: ENZUINC-US (18978)                  Loc: US / Los Angeles         OS: Ubuntu     Tags: http, smtp, ssh
5.79.68.175     Title: dc414 | Your Milwaukee area DEFCON group.  SSL: dc414.org + dc414.org+                       AS: LEASEWEB-NL (60781)                 Loc: NL / Amsterdam           OS: N/A        Tags: http, https
```

Cheers

**Comment by gelim** [comment]
closed as resolved.
