### ISSUE TITLE
SyntaxError: invalid syntax  line 87 print final_line.strip("\t"

### ISSUE THREAD

**Issue by Labs22** [gelim/censys#5]
File ".\censys_io.py", line 87 print final_line.strip("\t") ^ SyntaxError: invalid syntax

How I can fix it?

Running on windows 10 python 3.7 and all requirements installed

**Comment by hjacquemin** [comment]
for all the print line, just add () to have print(final_line.strip("\t"))

also, change the the library name from/to

import urllib --> import urllib.request

In your virtual env, install with pip quote censys and colorama, I got issue with requirements.txt file.

**Comment by not-devil** [comment]
Traceback (most recent call last):
  File "/home/asmodeus/Desktop/censys/censys_io.py", line 6, in <module>
    from censys.ipv4     import *
ModuleNotFoundError: No module named 'censys.ipv4'
